config/routes.rb
  RaceRegistration::Application.routes.draw do
  resources :registrations

  resources :pricing_types

  resources :races_registrations

  resources :states

  resources :age_group_details

  resources :age_group_categories

  resources :pricings

  resources :races

  resources :sports

  resources :events

  resources :organizers

  resources :users

  match '/register_step_1', :to => 'registrations#register_step_1', :as => "register_step_1"
  match '/register_step_2', :to => 'registrations#register_step_2', :as => "register_step_2"

end

app/models/age_group_category.rb
class AgeGroupCategory < ActiveRecord::Base

  def age_group_category_display_values
      "#{name}"
  end
  has_many :age_group_details
  accepts_nested_attributes_for :age_group_details


  has_many :races
end

app/models/age_group_detail.rb
class AgeGroupDetail < ActiveRecord::Base
   has_many :registrations
  belongs_to :age_group_category

end

app/models/event.rb
class Event < ActiveRecord::Base
  def event_display_values
    "#{name} - #{address}, #{city}, #{state_cd}"
  end
   belongs_to :organizer
   has_many :races
end

app/models/organizer.rb
class Organizer < ActiveRecord::Base
  has_many :events
  def organizer_display_values
           "#{name} - #{city}, #{state_cd}"
  end

  validates_format_of :email_address, :allow_blank=>false, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
  validates_format_of :phone_num, :allow_blank =>:true, :with => /^\([0-9]{3}\)[ ][0-9]{3}[-][0-9]{4}$/, :message => 'Please use format (xxx) xxx-xxxx for phone number.'
  validates_format_of :cell_num, :allow_blank =>:true, :with => /^\([0-9]{3}\)[ ][0-9]{3}[-][0-9]{4}$/, :message => 'Please use format (xxx) xxx-xxxx for cell number.'

end

app/models/pricing.rb
class Pricing < ActiveRecord::Base
  def user_display_values
    "#{first_name} #{last_name}, #{gender}, #{city}, #{state_cd}, #{born_on}"
  end
   belongs_to :race
end

app/models/pricing_type.rb
class PricingType < ActiveRecord::Base
  def pricing_type_display_values
    "#{pricing_type}"
  end
end

app/models/race.rb
class Race < ActiveRecord::Base
  def race_display_values
    "#{name}, #{starts_at}, #{description}"
  end
   has_many :pricings
   has_and_belongs_to_many :registrations
   belongs_to :event
   belongs_to :age_group_category
   belongs_to :sport
end

app/models/races_registration.rb
class RacesRegistration < ActiveRecord::Base
end

app/models/races_registrations.rb
class RacesRegistrations < ActiveRecord::Base
end

app/models/registration.rb
class Registration < ActiveRecord::Base
   has_one :age_group_detail
  has_and_belongs_to_many :races
end

app/models/sport.rb
class Sport < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  def user_display_values
    "#{first_name} #{last_name}, #{gender}, #{city}, #{state_cd}, #{born_on}"
  end
  validates_format_of :email_address, :allow_blank=>false, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
  validates_format_of :phone_num, :allow_blank =>:true, :with => /^\([0-9]{3}\)[ ][0-9]{3}[-][0-9]{4}$/, :message => 'Please use format (xxx) xxx-xxxx for phone number.'
  validates_format_of :cell_num, :allow_blank =>:true, :with => /^\([0-9]{3}\)[ ][0-9]{3}[-][0-9]{4}$/, :message => 'Please use format (xxx) xxx-xxxx for cell number.'

  has_many :registrations
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  # GET /races
  # GET /races.json
  def index
    @races = Race.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @races }
    end
  end

  # GET /races/1
  # GET /races/1.json
  def show
    @race = Race.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @race }
    end
  end

  # GET /races/new
  # GET /races/new.json
  def new
    @race = Race.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @race }
    end
  end

  # GET /races/1/edit
  def edit
    @race = Race.find(params[:id])
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(params[:race])

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, :notice => 'Race was successfully created.' }
        format.json { render :json => @race, :status => :created, :location => @race }
      else
        format.html { render :action => "new" }
        format.json { render :json => @race.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /races/1
  # PUT /races/1.json
  def update
    @race = Race.find(params[:id])

    respond_to do |format|
      if @race.update_attributes(params[:race])
        format.html { redirect_to @race, :notice => 'Race was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @race.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race = Race.find(params[:id])
    @race.destroy

    respond_to do |format|
      format.html { redirect_to races_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/helpers/pricings_helper.rb
module PricingsHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/races/_form.html.erb
<%= form_for(@race) do |f| %>
  <% if @race.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@race.errors.count, "error") %> prohibited this race from being saved:</h2>

      <ul>
      <% @race.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label :event_id %>
      <%= f.collection_select :event_id, Event.all, :id, :event_display_values, :prompt => "Select an event" %>
    </div>
    <div>
      <%= f.label :sport_id %>
      <%= f.collection_select :sport_id, Sport.all, :id, :name, :prompt => "Select a sport" %>
    </div>
    <div class="field">
      <%= f.label :age_group_category_id %>
      <%= f.collection_select :age_group_category_id, AgeGroupCategory.all, :id, :name, :prompt => "Select an age group category"%>
    </div>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :starts_at %>
      <%= f.text_field :starts_at %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>


    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/races/edit.html.erb
<h1>Editing race</h1>

<%= render 'form' %>

<%= link_to 'Show', @race %> |
<%= link_to 'Back', races_path %>

app/views/races/index.html.erb
<h1>Listing races</h1>

<table>
  <tr>
    <th>event_id</th>
    <th>sport_id</th>
    <th>age_group_category_id</th>
    <th>name</th>
    <th>starts_at</th>
    <th>description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @races.each do |race| %>
  <tr>
    <td><%= race.event_id %></td>
    <td><%= race.sport_id %></td>
    <td><%= race.age_group_category_id %></td>
    <td><%= race.name %></td>
    <td><%= race.starts_at %></td>
    <td><%= race.description %></td>

     <td><%= link_to 'Show', race %></td>
    <td><%= link_to 'Edit', edit_race_path(race) %></td>
    <td><%= link_to 'Destroy', race, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Race', new_race_path %>

app/views/races/new.html.erb
<h1>New race</h1>

<%= render 'form' %>

<%= link_to 'Back', races_path %>

app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>event_id:</b>
  <%= @race.event_id %>
</p>

<p>
  <b>sport_id:</b>
  <%= @race.sport_id %>
</p>
<p>
  <b>age_group_category_id:</b>
  <%= @race.age_group_category_id %>
</p>
<p>
  <b>name:</b>
  <%= @race.name %>
</p>
<p>
  <b>starts_at:</b>
  <%= @race.starts_at %>
</p>
<p>
  <b>description:</b>
  <%= @race.description %>
</p>


<%= link_to 'Edit', edit_race_path(@race) %> |
<%= link_to 'Back', races_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :middle_init %>
      <%= f.text_field :middle_init %>
    </div>
    <div class="field">
      <%= f.label :born_on %>
      <%= f.text_field :born_on %>
    </div>
    <div class="field">
      <%= f.label :gender %>
      <%= f.text_field :gender %>
   </div>
    <div class="field">
      <%= f.label :address1 %>
      <%= f.text_field :address1 %>
    </div>
    <div class="field">
      <%= f.label :address2 %>
      <%= f.text_field :address2 %>
    </div>
    <div class="field">
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>   <div class="field">
      <%= f.label :state_cd %>
    <%= f.collection_select :state_cd, State.all, :abbrev, :name, :prompt => "Select a state" %>
   </div>
   <div class="field">
  <%= f.label :zip_cd %>
  <%= f.text_field :zip_cd %>
     </div>
     <div class="field">
       <%= f.label :phone_num %>
       <%= f.text_field :phone_num %>
   </div>
    <div class="field">
      <%= f.label :cell_num %>
      <%= f.text_field :cell_num %>
    </div>
    <div class="field">
      <%= f.label :email_address %>
      <%= f.text_field :email_address %>
    </div>
    <div class="field">
  <%= f.label :password %>
  <%= f.text_field :password %>
</div>
    <div class="field">
      <%= f.label :swim_100m_time %>
      <%= f.text_field :swim_100m_time %>
    </div>

    <div class="field">
      <%= f.label :treat_as_user %>
      <%= f.text_field :treat_as_user %>
    </div>
    <div class="field">
      <%= f.label :notify_about_events %>
      <%= f.text_field :notify_about_events %>
    </div>


    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>

    <th>first</th>
    <th>last</th>
    <th>middle init</th>
    <th>dob</th>
    <th>M/F</th>
    <th>addr1</th>
    <th>addr2</th>
    <th>city</th>
    <th>state</th>
    <th>zip</th>
    <th>state</th>
    <th>phone</th>
    <th>cell</th>
    <th>swim 100m</th>
    <th>create user</th>
    <th>notify about other events</th>
    <th></th>

    <th></th>
    <th></th>
    <th></th>


  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.middle_init %></td>
    <td><%= user.born_on %></td>
    <td><%= user.gender %></td>
    <td><%= user.address1 %></td>
    <td><%= user.address2 %></td>
    <td><%= user.city %></td>
    <td><%= user.state_cd %></td>
    <td><%= user.zip_cd %></td>
    <td><%= user.phone_num %></td>
    <td><%= user.cell_num %></td>
    <td><%= user.email_address %></td>
    <td><%= user.swim_100m_time %></td>
    <td><%= user.treat_as_user %></td>
    <td><%= user.notify_about_events %></td>
     <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>first_name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>last:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>middle_init:</b>
  <%= @user.middle_init %>
</p>

<p>
  <b>born_on:</b>
  <%= @user.born_on %>
</p>

<p>
  <b>gender:</b>
  <%= @user.gender %>
</p>

<p>
  <b>address1:</b>
  <%= @user.address1 %>
</p>

<p>
  <b>address2:</b>
  <%= @user.address2 %>
</p>

<p>
  <b>city:</b>
  <%= @user.city %>
</p>

<p>
  <b>state_cd:</b>
  <%= @user.state_cd %>
</p>

<p>
  <b>zip_cd:</b>
  <%= @user.zip_cd %>
</p>

<p>
  <b>phone_num:</b>
  <%= @user.phone_num %>
</p>

<p>
  <b>cell_num:</b>
  <%= @user.cell_num %>
</p>

<p>
  <b>email_address:</b>
  <%= @user.email_address %>
</p>

<p>
  <b>password:</b>
  <%= @user.password %>
</p>

<p>
  <b>swim_100m_time:</b>
  <%= @user.swim_100m_time %>
</p>

<p>
  <b>treat_as_user:</b>
  <%= @user.treat_as_user %>
</p>


<p>
  <b>notify_about_events:</b>
  <%= @user.notify_about_events %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>