config/routes.rb
  RaceRegistration::Application.routes.draw do
  resources :registrations

  resources :pricing_types

  resources :races_registrations

  resources :states

  resources :age_group_details

  resources :age_group_categories

  resources :pricings

  resources :races

  resources :sports

  resources :events

  resources :organizers

  resources :users

  match '/register_step_1', :to => 'registrations#register_step_1', :as => "register_step_1"
  match '/register_step_2', :to => 'registrations#register_step_2', :as => "register_step_2"

end

app/models/age_group_category.rb
class AgeGroupCategory < ActiveRecord::Base

  def age_group_category_display_values
      "#{name}"
  end
  has_many :age_group_details
  accepts_nested_attributes_for :age_group_details


  has_many :races
end

app/models/age_group_detail.rb
class AgeGroupDetail < ActiveRecord::Base
   has_many :registrations
  belongs_to :age_group_category

end

app/models/event.rb
class Event < ActiveRecord::Base
  def event_display_values
    "#{name} - #{address}, #{city}, #{state_cd}"
  end
   belongs_to :organizer
   has_many :races
end

app/models/organizer.rb
class Organizer < ActiveRecord::Base
  has_many :events
  def organizer_display_values
           "#{name} - #{city}, #{state_cd}"
  end

  validates_format_of :email_address, :allow_blank=>false, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
  validates_format_of :phone_num, :allow_blank =>:true, :with => /^\([0-9]{3}\)[ ][0-9]{3}[-][0-9]{4}$/, :message => 'Please use format (xxx) xxx-xxxx for phone number.'
  validates_format_of :cell_num, :allow_blank =>:true, :with => /^\([0-9]{3}\)[ ][0-9]{3}[-][0-9]{4}$/, :message => 'Please use format (xxx) xxx-xxxx for cell number.'

end

app/models/pricing.rb
class Pricing < ActiveRecord::Base
  def user_display_values
    "#{first_name} #{last_name}, #{gender}, #{city}, #{state_cd}, #{born_on}"
  end
   belongs_to :race
end

app/models/pricing_type.rb
class PricingType < ActiveRecord::Base
  def pricing_type_display_values
    "#{pricing_type}"
  end
end

app/models/race.rb
class Race < ActiveRecord::Base
  def race_display_values
    "#{name}, #{starts_at}, #{description}"
  end
   has_many :pricings
   has_and_belongs_to_many :registrations
   belongs_to :event
   belongs_to :age_group_category
   belongs_to :sport
end

app/models/races_registration.rb
class RacesRegistration < ActiveRecord::Base
end

app/models/races_registrations.rb
class RacesRegistrations < ActiveRecord::Base
end

app/models/registration.rb
class Registration < ActiveRecord::Base
   has_one :age_group_detail
  has_and_belongs_to_many :races
end

app/models/sport.rb
class Sport < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  def user_display_values
    "#{first_name} #{last_name}, #{gender}, #{city}, #{state_cd}, #{born_on}"
  end
  validates_format_of :email_address, :allow_blank=>false, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
  validates_format_of :phone_num, :allow_blank =>:true, :with => /^\([0-9]{3}\)[ ][0-9]{3}[-][0-9]{4}$/, :message => 'Please use format (xxx) xxx-xxxx for phone number.'
  validates_format_of :cell_num, :allow_blank =>:true, :with => /^\([0-9]{3}\)[ ][0-9]{3}[-][0-9]{4}$/, :message => 'Please use format (xxx) xxx-xxxx for cell number.'

  has_many :registrations
end

app/controllers/organizers_controller.rb
class OrganizersController < ApplicationController
  # GET /organizers
  # GET /organizers.json
  def index
    @organizers = Organizer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @organizers }
    end
  end

  # GET /organizers/1
  # GET /organizers/1.json
  def show
    @organizer = Organizer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @organizer }
    end
  end

  # GET /organizers/new
  # GET /organizers/new.json
  def new
    @organizer = Organizer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @organizer }
    end
  end

  # GET /organizers/1/edit
  def edit
    @organizer = Organizer.find(params[:id])
  end

  # POST /organizers
  # POST /organizers.json
  def create
    @organizer = Organizer.new(params[:organizer])

    respond_to do |format|
      if @organizer.save
        format.html { redirect_to @organizer, :notice => 'Organizer was successfully created.' }
        format.json { render :json => @organizer, :status => :created, :location => @organizer }
      else
        format.html { render :action => "new" }
        format.json { render :json => @organizer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /organizers/1
  # PUT /organizers/1.json
  def update
    @organizer = Organizer.find(params[:id])

    respond_to do |format|
      if @organizer.update_attributes(params[:organizer])
        format.html { redirect_to @organizer, :notice => 'Organizer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @organizer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /organizers/1
  # DELETE /organizers/1.json
  def destroy
    @organizer = Organizer.find(params[:id])
    @organizer.destroy

    respond_to do |format|
      format.html { redirect_to organizers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  # GET /races
  # GET /races.json
  def index
    @races = Race.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @races }
    end
  end

  # GET /races/1
  # GET /races/1.json
  def show
    @race = Race.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @race }
    end
  end

  # GET /races/new
  # GET /races/new.json
  def new
    @race = Race.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @race }
    end
  end

  # GET /races/1/edit
  def edit
    @race = Race.find(params[:id])
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(params[:race])

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, :notice => 'Race was successfully created.' }
        format.json { render :json => @race, :status => :created, :location => @race }
      else
        format.html { render :action => "new" }
        format.json { render :json => @race.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /races/1
  # PUT /races/1.json
  def update
    @race = Race.find(params[:id])

    respond_to do |format|
      if @race.update_attributes(params[:race])
        format.html { redirect_to @race, :notice => 'Race was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @race.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race = Race.find(params[:id])
    @race.destroy

    respond_to do |format|
      format.html { redirect_to races_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/helpers/pricings_helper.rb
module PricingsHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/organizers/_form.html.erb
<%= form_for(@organizer) do |f| %>
  <% if @organizer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organizer.errors.count, "error") %> prohibited this organizer from being saved:</h2>

      <ul>
      <% @organizer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :website %><br />
      <%= f.text_field :website %>
    </div>
    <div class="field">
      <%= f.label :phone_num %><br />
      <%= f.text_field :phone_num %>
    </div>
    <div class="field">
      <%= f.label :cell_num %><br />
      <%= f.text_field :cell_num %>
    </div>
    <div class="field">
      <%= f.label :email_address %><br />
      <%= f.text_field :email_address %>
    </div>
    <div class="field">
      <%= f.label :contact_name %><br />
      <%= f.text_field :contact_name %>
    </div>
    <div class="field">
      <%= f.label :address1 %><br />
      <%= f.text_field :address1 %>
    </div>
    <div class="field">
      <%= f.label :address2 %><br />
      <%= f.text_field :address2 %>
    </div>
    <div class="field">
      <%= f.label :city %><br />
      <%= f.text_field :city %>
    </div>
    <div class="field">
      <%= f.label :state_cd %><br />
      <%= f.collection_select :state_cd, State.all, :abbrev, :name, :prompt => "Select a state" %>
    </div>
    <div class="field">
      <%= f.label :zip_cd %><br />
      <%= f.text_field :zip_cd %>
 </div>
    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizers/edit.html.erb
<h1>Editing organizer</h1>

<%= render 'form' %>

<%= link_to 'Show', @organizer %> |
<%= link_to 'Back', organizers_path %>

app/views/organizers/index.html.erb
<h1>Listing organizers</h1>

<table>
  <tr>
    <th>name</th>
    <th>website</th>
    <th>phone</th>
    <th>cell</th>
    <th>email</th>
    <th>contact</th>
    <th>address1</th>
    <th>address2</th>
    <th>city</th>
    <th>state</th>
    <th>zip</th>
    <th></th>
    <th></th>
    <th></th>


  </tr>

<% @organizers.each do |organizer| %>
  <tr>
  <td><%= organizer.name %></td>
  <td><%= organizer.website %></td>
  <td><%= organizer.phone_num %></td>
  <td><%= organizer.cell_num %></td>
  <td><%= organizer.email_address %></td>
  <td><%= organizer.contact_name %></td>
  <td><%= organizer.address1 %></td>
  <td><%= organizer.address2 %></td>
  <td><%= organizer.city %></td>
  <td><%= organizer.state_cd %></td>
  <td><%= organizer.zip_cd %></td>

  <td><%= link_to 'Show', organizer %></td>
    <td><%= link_to 'Edit', edit_organizer_path(organizer) %></td>
    <td><%= link_to 'Destroy', organizer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Organizer', new_organizer_path %>

app/views/organizers/new.html.erb
<h1>New organizer</h1>

<%= render 'form' %>

<%= link_to 'Back', organizers_path %>

app/views/organizers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @organizer.name %>
</p>
<p>
  <b>Website:</b>
  <%= @organizer.website %>
</p>
<p>
  <b>Phone Number:</b>
  <%= @organizer.phone_num %>
</p>
<p>
  <b>Cell Number:</b>
  <%= @organizer.cell_num %>
</p>
<p>
  <b>Email:</b>
  <%= @organizer.email_address %>
</p>
<p>
  <b>Contact:</b>
  <%= @organizer.contact_name %>
</p>
<p>
  <b>Addr1:</b>
  <%= @organizer.address1 %>
</p>
<p>
  <b>Addr2:</b>
  <%= @organizer.address2 %>
</p>
<p>
  <b>City:</b>
  <%= @organizer.city %>
</p>
<p>
  <b>State:</b>
  <%= @organizer.state_cd %>
</p>
<p>
  <b>Zip</b>
  <%= @organizer.zip_cd %>
</p>


<%= link_to 'Edit', edit_organizer_path(@organizer) %> |
<%= link_to 'Back', organizers_path %>