config/routes.rb
  RaceRegistration::Application.routes.draw do
  resources :registrations

  resources :pricing_types

  resources :races_registrations

  resources :states

  resources :age_group_details

  resources :age_group_categories

  resources :pricings

  resources :races

  resources :sports

  resources :events

  resources :organizers

  resources :users

  match '/register_step_1', :to => 'registrations#register_step_1', :as => "register_step_1"
  match '/register_step_2', :to => 'registrations#register_step_2', :as => "register_step_2"

end

app/models/age_group_category.rb
class AgeGroupCategory < ActiveRecord::Base

  def age_group_category_display_values
      "#{name}"
  end
  has_many :age_group_details
  accepts_nested_attributes_for :age_group_details


  has_many :races
end

app/models/age_group_detail.rb
class AgeGroupDetail < ActiveRecord::Base
   has_many :registrations
  belongs_to :age_group_category

end

app/models/event.rb
class Event < ActiveRecord::Base
  def event_display_values
    "#{name} - #{address}, #{city}, #{state_cd}"
  end
   belongs_to :organizer
   has_many :races
end

app/models/organizer.rb
class Organizer < ActiveRecord::Base
  has_many :events
  def organizer_display_values
           "#{name} - #{city}, #{state_cd}"
  end

  validates_format_of :email_address, :allow_blank=>false, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
  validates_format_of :phone_num, :allow_blank =>:true, :with => /^\([0-9]{3}\)[ ][0-9]{3}[-][0-9]{4}$/, :message => 'Please use format (xxx) xxx-xxxx for phone number.'
  validates_format_of :cell_num, :allow_blank =>:true, :with => /^\([0-9]{3}\)[ ][0-9]{3}[-][0-9]{4}$/, :message => 'Please use format (xxx) xxx-xxxx for cell number.'

end

app/models/pricing.rb
class Pricing < ActiveRecord::Base
  def user_display_values
    "#{first_name} #{last_name}, #{gender}, #{city}, #{state_cd}, #{born_on}"
  end
   belongs_to :race
end

app/models/pricing_type.rb
class PricingType < ActiveRecord::Base
  def pricing_type_display_values
    "#{pricing_type}"
  end
end

app/models/race.rb
class Race < ActiveRecord::Base
  def race_display_values
    "#{name}, #{starts_at}, #{description}"
  end
   has_many :pricings
   has_and_belongs_to_many :registrations
   belongs_to :event
   belongs_to :age_group_category
   belongs_to :sport
end

app/models/races_registration.rb
class RacesRegistration < ActiveRecord::Base
end

app/models/races_registrations.rb
class RacesRegistrations < ActiveRecord::Base
end

app/models/registration.rb
class Registration < ActiveRecord::Base
   has_one :age_group_detail
  has_and_belongs_to_many :races
end

app/models/sport.rb
class Sport < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  def user_display_values
    "#{first_name} #{last_name}, #{gender}, #{city}, #{state_cd}, #{born_on}"
  end
  validates_format_of :email_address, :allow_blank=>false, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
  validates_format_of :phone_num, :allow_blank =>:true, :with => /^\([0-9]{3}\)[ ][0-9]{3}[-][0-9]{4}$/, :message => 'Please use format (xxx) xxx-xxxx for phone number.'
  validates_format_of :cell_num, :allow_blank =>:true, :with => /^\([0-9]{3}\)[ ][0-9]{3}[-][0-9]{4}$/, :message => 'Please use format (xxx) xxx-xxxx for cell number.'

  has_many :registrations
end

app/controllers/age_group_categories_controller.rb
class AgeGroupCategoriesController < ApplicationController
  # GET /age_group_categories
  # GET /age_group_categories.json
  def index
    @age_group_categories = AgeGroupCategory.all
     respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @age_group_categories }
    end
  end

  # GET /age_group_categories/1
  # GET /age_group_categories/1.json
  def show
    @age_group_category = AgeGroupCategory.find(params[:id])
    @age_group_category.age_group_details.build    if @age_group_category.age_group_details.nil?


    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @age_group_category }
    end
  end

  # GET /age_group_categories/new
  # GET /age_group_categories/new.json
  def new
    @age_group_category = AgeGroupCategory.new
    @age_group_category.age_group_details.build    if @age_group_category.age_group_details.nil?

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @age_group_category }
    end
  end

  # GET /age_group_categories/1/edit
  def edit
    @age_group_category = AgeGroupCategory.find(params[:id])
    @age_group_category.age_group_details.build    if @age_group_category.age_group_details.nil?
  end

  # POST /age_group_categories
  # POST /age_group_categories.json
  def create
    @age_group_category = AgeGroupCategory.new(params[:age_group_category])
    @age_group_category.age_group_details.build    if @age_group_category.age_group_details.nil?

    respond_to do |format|
      if @age_group_category.save
        format.html { redirect_to @age_group_category, :notice => 'Age group category was successfully created.' }
        format.json { render :json => @age_group_category, :status => :created, :location => @age_group_category }
      else
        format.html { render :action => "new" }
        format.json { render :json => @age_group_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /age_group_categories/1
  # PUT /age_group_categories/1.json
  def update
    @age_group_category = AgeGroupCategory.find(params[:id])
    @age_group_category.age_group_details.build    if @age_group_category.age_group_details.nil?

    respond_to do |format|
      if @age_group_category.update_attributes(params[:age_group_category])
        format.html { redirect_to @age_group_category, :notice => 'Age group category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @age_group_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /age_group_categories/1
  # DELETE /age_group_categories/1.json
  def destroy
    @age_group_category = AgeGroupCategory.find(params[:id])
    @age_group_category.destroy

    respond_to do |format|
      format.html { redirect_to age_group_categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/age_group_categories_helper.rb
module AgeGroupCategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/helpers/pricings_helper.rb
module PricingsHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/age_group_categories/_form.html.erb
<%= nested_form_for @age_group_category, :validate => true do |f| %>
  <% if @age_group_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@age_group_category.errors.count, "error") %> prohibited this age_group_category from being saved:</h2>

      <ul>
      <% @age_group_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>

    <table>
      <tr>

        <td>gender </td>
        <td>min_age</td>
        <td>max_age</td>
        <td>comments</td>
        <td></td>


      </tr>
      <%= f.fields_for :age_group_details do |age_group_detail_form| %>
       <tr>
          <td><%= age_group_detail_form.text_field :gender %> </td>
          <td><%= age_group_detail_form.text_field :min_age %></td>
          <td><%= age_group_detail_form.text_field :max_age %></td>
          <td><%= age_group_detail_form.text_field :comments %></td>
         <td><%= age_group_detail_form.link_to_remove "Remove this age group detail record" %></td>
        </tr>
       <% end %>

    </table>
    <%= f.link_to_add "Add an age group detail record", :age_group_details %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/age_group_categories/edit.html.erb
<h1>Editing age_group_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @age_group_category %> |
<%= link_to 'Back', age_group_categories_path %>

app/views/age_group_categories/index.html.erb
<h1>Listing age_group_categories</h1>

<table>
  <tr>
    <th>name:</th>
    <th>description:</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @age_group_categories.each do |age_group_category| %>
  <tr>
    <td><%= age_group_category.name %></td>
    <td><%= age_group_category.description %></td>
    <td><%= link_to 'Show', age_group_category %></td>
    <td><%= link_to 'Edit', edit_age_group_category_path(age_group_category) %></td>
    <td><%= link_to 'Destroy', age_group_category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Age group category', new_age_group_category_path %>

app/views/age_group_categories/new.html.erb
<h1>New age_group_category</h1>

<%= render 'form' %>

<%= link_to 'Back', age_group_categories_path %>

app/views/age_group_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>name:</b>
  <%= @age_group_category.name %>
</p>

<p>
  <b>description:</b>
  <%= @age_group_category.description %>
</p>
<%= link_to 'Edit', edit_age_group_category_path(@age_group_category) %> |
<%= link_to 'Back', age_group_categories_path %>